DROP TABLE IF EXISTS author;
CREATE TABLE author(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS genre;
CREATE TABLE genre(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS book;
CREATE TABLE book(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), AUTHORID BIGINT, GENREID BIGINT);

